/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.interfazfigurasgeometricas;
import javax.swing.JOptionPane;
/**
 *
 * @author Oscar
 */
public class FormFiguras extends javax.swing.JFrame {

    /**
     * Creates new form FormFiguras
     */
    public FormFiguras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        btnCirculo = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        btnCuadrado = new javax.swing.JButton();
        btnRectangulo = new javax.swing.JButton();
        BorrarTodo = new javax.swing.JButton();
        BorrarCirculo = new javax.swing.JButton();
        BorrarTriangulo = new javax.swing.JButton();
        BorrarCuadrado = new javax.swing.JButton();
        BorrarRectangulo = new javax.swing.JButton();
        areaCirculo = new javax.swing.JTextField();
        areaCuadrado = new javax.swing.JTextField();
        perimetroCuadrado = new javax.swing.JTextField();
        perimetroCirculo = new javax.swing.JTextField();
        Hipotenusa = new javax.swing.JTextField();
        perimetroRectangulo = new javax.swing.JTextField();
        areaRectangulo = new javax.swing.JTextField();
        perimetroTriangulo = new javax.swing.JTextField();
        areaTriangulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TipoTriangulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCirculo.setText("Círculo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnTriangulo.setText("Triángulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        btnCuadrado.setText("Cuadrado");
        btnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoActionPerformed(evt);
            }
        });

        btnRectangulo.setText("Rectángulo");
        btnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloActionPerformed(evt);
            }
        });

        BorrarTodo.setText("Borrar todo");
        BorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarTodoActionPerformed(evt);
            }
        });

        BorrarCirculo.setText("Borrar círculo");
        BorrarCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCirculoActionPerformed(evt);
            }
        });

        BorrarTriangulo.setText("Borrar triángulo");
        BorrarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarTrianguloActionPerformed(evt);
            }
        });

        BorrarCuadrado.setText("Borrar cuadrado");
        BorrarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCuadradoActionPerformed(evt);
            }
        });

        BorrarRectangulo.setText("Borrar rectángulo");
        BorrarRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarRectanguloActionPerformed(evt);
            }
        });

        areaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTrianguloActionPerformed(evt);
            }
        });

        jLabel1.setText("Área");

        jLabel2.setText("Perímetro");

        jLabel3.setText("Hipotenusa");

        jLabel4.setText("Tipo de Triángulo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(areaCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(perimetroCirculo)))
                                    .addComponent(btnCirculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(areaTriangulo)
                                    .addComponent(perimetroTriangulo)
                                    .addComponent(Hipotenusa)
                                    .addComponent(TipoTriangulo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(BorrarCirculo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(BorrarTriangulo)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(BorrarCuadrado))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(areaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perimetroCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BorrarRectangulo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(perimetroRectangulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(areaRectangulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRectangulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCuadrado)
                                .addGap(18, 18, 18)
                                .addComponent(areaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(perimetroCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRectangulo)
                                .addGap(18, 18, 18)
                                .addComponent(areaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(perimetroRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTriangulo)
                                .addGap(18, 18, 18)
                                .addComponent(areaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(perimetroTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCirculo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perimetroCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrarCirculo)
                    .addComponent(BorrarTriangulo)
                    .addComponent(BorrarCuadrado)
                    .addComponent(BorrarRectangulo))
                .addGap(45, 45, 45)
                .addComponent(BorrarTodo)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        double base, altura;
        base = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el valor de la base del triángulo: "));
        altura = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el valor de la altura del triángulo: "));
        areaTriangulo.setText(String.valueOf((triangulo.calcularArea(base,altura))*100.0/100.0));
        perimetroTriangulo.setText(String.valueOf((triangulo.calcularPerimetro(base,altura)*100.0/100.0)));
        Hipotenusa.setText(String.valueOf(triangulo.calcularHipotenusa(base,altura)));
        TipoTriangulo.setText(String.valueOf(triangulo.determinarTipoTriangulo(base,altura)));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void areaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTrianguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
           int radio;
           radio = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese el radio del círculo"));
           areaCirculo.setText(String.valueOf((circulo.calcularArea(radio)*100.0)/100.0));
           perimetroCirculo.setText(String.valueOf((circulo.calcularPerimetro(radio)*100.0/100.0)));
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        double lado;
        lado = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingrese el valor del lado del cuadrado: "));
        areaCuadrado.setText(String.valueOf((cuadrado.calcularArea(lado)*100.0/100.0)));
        perimetroCuadrado.setText(String.valueOf((cuadrado.calcularPerimetro(lado)*100.0/100.0)));
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        double base,altura;
        base = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingrese el valor de la base del rectángulo: "));
        altura = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingrese el valor de la altura del rectángulo: "));
        areaRectangulo.setText(String.valueOf((rectangulo.calcularArea(base,altura))*100.0/100.0));
        perimetroRectangulo.setText(String.valueOf((rectangulo.calcularPerimetro(base,altura))*100.0/100.0));
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void BorrarCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCirculoActionPerformed
        areaCirculo.setText("");
        perimetroCirculo.setText("");
    }//GEN-LAST:event_BorrarCirculoActionPerformed

    private void BorrarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarTrianguloActionPerformed
        areaTriangulo.setText("");
        perimetroTriangulo.setText("");    
        Hipotenusa.setText("");
        TipoTriangulo.setText("");
    }//GEN-LAST:event_BorrarTrianguloActionPerformed

    private void BorrarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCuadradoActionPerformed
        areaCuadrado.setText("");
        perimetroCuadrado.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarCuadradoActionPerformed

    private void BorrarRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarRectanguloActionPerformed
        areaRectangulo.setText("");
        perimetroRectangulo.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarRectanguloActionPerformed

    private void BorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarTodoActionPerformed
        areaCirculo.setText("");
        perimetroCirculo.setText("");        
        areaCuadrado.setText("");
        perimetroCuadrado.setText("");        
        areaTriangulo.setText("");
        perimetroTriangulo.setText("");        
        areaRectangulo.setText("");
        perimetroRectangulo.setText("");
        Hipotenusa.setText("");
        TipoTriangulo.setText("");
    }//GEN-LAST:event_BorrarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFiguras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFiguras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarCirculo;
    private javax.swing.JButton BorrarCuadrado;
    private javax.swing.JButton BorrarRectangulo;
    private javax.swing.JButton BorrarTodo;
    private javax.swing.JButton BorrarTriangulo;
    private javax.swing.JTextField Hipotenusa;
    private javax.swing.JTextField TipoTriangulo;
    private javax.swing.JTextField areaCirculo;
    private javax.swing.JTextField areaCuadrado;
    private javax.swing.JTextField areaRectangulo;
    private javax.swing.JTextField areaTriangulo;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField perimetroCirculo;
    private javax.swing.JTextField perimetroCuadrado;
    private javax.swing.JTextField perimetroRectangulo;
    private javax.swing.JTextField perimetroTriangulo;
    // End of variables declaration//GEN-END:variables
}
